package com.example.demo.dao;

import com.example.demo.entity.FantasyRole;
import org.springframework.data.repository.query.Param;

import javax.annotation.Resource;
import java.util.List;

@Resource
public interface FantasyRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_role
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_role
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    int insert(FantasyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_role
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    FantasyRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_role
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    List<FantasyRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_role
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    int updateByPrimaryKey(FantasyRole record);

    List<FantasyRole> findListByUserId(@Param(value = "userId") Integer userId);
}