package com.example.demo.dao;

import com.example.demo.entity.FantasyPermission;
import org.apache.ibatis.annotations.Param;

import javax.annotation.Resource;
import java.util.List;

@Resource
public interface FantasyPermissionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_permission
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_permission
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    int insert(FantasyPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_permission
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    FantasyPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_permission
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    List<FantasyPermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fantasy_permission
     *
     * @mbg.generated Wed Jul 25 17:39:01 CST 2018
     */
    int updateByPrimaryKey(FantasyPermission record);

    List<FantasyPermission> findListByRoleId(Integer roleId);

    List<FantasyPermission> findListByUserId(@Param(value = "userId") Integer userId);
}